// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobilePhoneStore.Models;

namespace MobilePhoneStore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240507145733_SecondMigration")]
    partial class SecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MobilePhoneStore.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("MobilePhoneStore.Models.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "China",
                            Name = "Huawei"
                        },
                        new
                        {
                            Id = 2,
                            Country = "China",
                            Name = "Xiaomi"
                        },
                        new
                        {
                            Id = 3,
                            Country = "China",
                            Name = "Honor"
                        },
                        new
                        {
                            Id = 4,
                            Country = "SAD",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Japan",
                            Name = "Samsung"
                        });
                });

            modelBuilder.Entity("MobilePhoneStore.Models.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableQuantity = 17,
                            ManufacturerId = 4,
                            Model = "13",
                            OperatingSystem = "IOS",
                            Photo = "https://istyle.rs/media/catalog/product/i/p/iphone_13_pink_pdp_image_position-1a__wwen_7_1_1.jpg",
                            Price = 530.0
                        },
                        new
                        {
                            Id = 2,
                            AvailableQuantity = 12,
                            ManufacturerId = 4,
                            Model = "14",
                            OperatingSystem = "IOS",
                            Photo = "https://istyle.rs/media/catalog/product/i/p/iphone_13_pink_pdp_image_position-1a__wwen_7_1_1.jpg",
                            Price = 625.0
                        },
                        new
                        {
                            Id = 3,
                            AvailableQuantity = 10,
                            ManufacturerId = 4,
                            Model = "15 Pro Max",
                            OperatingSystem = "IOS",
                            Photo = "https://istyle.rs/media/catalog/product/i/p/iphone_13_pink_pdp_image_position-1a__wwen_7_1_1.jpg",
                            Price = 1180.0
                        },
                        new
                        {
                            Id = 4,
                            AvailableQuantity = 4,
                            ManufacturerId = 4,
                            Model = "15",
                            OperatingSystem = "IOS",
                            Photo = "https://istyle.rs/media/catalog/product/i/p/iphone_13_pink_pdp_image_position-1a__wwen_7_1_1.jpg",
                            Price = 740.0
                        },
                        new
                        {
                            Id = 5,
                            AvailableQuantity = 7,
                            ManufacturerId = 5,
                            Model = "Galaxy Z Fold",
                            OperatingSystem = "Android",
                            Photo = "https://istyle.rs/media/catalog/product/i/p/iphone_13_pink_pdp_image_position-1a__wwen_7_1_1.jpg",
                            Price = 1250.0
                        },
                        new
                        {
                            Id = 6,
                            AvailableQuantity = 5,
                            ManufacturerId = 5,
                            Model = "Galaxy S24 Ultra",
                            OperatingSystem = "Android",
                            Photo = "https://istyle.rs/media/catalog/product/i/p/iphone_13_pink_pdp_image_position-1a__wwen_7_1_1.jpg",
                            Price = 1260.0
                        },
                        new
                        {
                            Id = 7,
                            AvailableQuantity = 0,
                            ManufacturerId = 5,
                            Model = "Galaxy S23 Ultra",
                            OperatingSystem = "Android",
                            Photo = "https://istyle.rs/media/catalog/product/i/p/iphone_13_pink_pdp_image_position-1a__wwen_7_1_1.jpg",
                            Price = 1552.0
                        },
                        new
                        {
                            Id = 8,
                            AvailableQuantity = 2,
                            ManufacturerId = 5,
                            Model = "Galaxy A55",
                            OperatingSystem = "Android",
                            Photo = "https://istyle.rs/media/catalog/product/i/p/iphone_13_pink_pdp_image_position-1a__wwen_7_1_1.jpg",
                            Price = 466.0
                        },
                        new
                        {
                            Id = 9,
                            AvailableQuantity = 7,
                            ManufacturerId = 1,
                            Model = "P60 Pro",
                            OperatingSystem = "Android",
                            Photo = "https://istyle.rs/media/catalog/product/i/p/iphone_13_pink_pdp_image_position-1a__wwen_7_1_1.jpg",
                            Price = 951.0
                        },
                        new
                        {
                            Id = 10,
                            AvailableQuantity = 5,
                            ManufacturerId = 1,
                            Model = "nova 11",
                            OperatingSystem = "Android",
                            Photo = "https://istyle.rs/media/catalog/product/i/p/iphone_13_pink_pdp_image_position-1a__wwen_7_1_1.jpg",
                            Price = 430.0
                        },
                        new
                        {
                            Id = 11,
                            AvailableQuantity = 0,
                            ManufacturerId = 1,
                            Model = "nova 10 SE",
                            OperatingSystem = "Android",
                            Photo = "https://istyle.rs/media/catalog/product/i/p/iphone_13_pink_pdp_image_position-1a__wwen_7_1_1.jpg",
                            Price = 291.0
                        },
                        new
                        {
                            Id = 12,
                            AvailableQuantity = 12,
                            ManufacturerId = 2,
                            Model = "14 Ultra",
                            OperatingSystem = "Android",
                            Photo = "https://istyle.rs/media/catalog/product/i/p/iphone_13_pink_pdp_image_position-1a__wwen_7_1_1.jpg",
                            Price = 1200.0
                        },
                        new
                        {
                            Id = 13,
                            AvailableQuantity = 15,
                            ManufacturerId = 2,
                            Model = "14",
                            OperatingSystem = "Android",
                            Photo = "https://istyle.rs/media/catalog/product/i/p/iphone_13_pink_pdp_image_position-1a__wwen_7_1_1.jpg",
                            Price = 855.0
                        },
                        new
                        {
                            Id = 14,
                            AvailableQuantity = 9,
                            ManufacturerId = 2,
                            Model = "13T Pro",
                            OperatingSystem = "Android",
                            Photo = "https://istyle.rs/media/catalog/product/i/p/iphone_13_pink_pdp_image_position-1a__wwen_7_1_1.jpg",
                            Price = 748.0
                        },
                        new
                        {
                            Id = 15,
                            AvailableQuantity = 12,
                            ManufacturerId = 3,
                            Model = "Magic6 Pro",
                            OperatingSystem = "Android",
                            Photo = "https://istyle.rs/media/catalog/product/i/p/iphone_13_pink_pdp_image_position-1a__wwen_7_1_1.jpg",
                            Price = 1090.0
                        },
                        new
                        {
                            Id = 16,
                            AvailableQuantity = 4,
                            ManufacturerId = 3,
                            Model = "90 5G",
                            OperatingSystem = "Android",
                            Photo = "https://istyle.rs/media/catalog/product/i/p/iphone_13_pink_pdp_image_position-1a__wwen_7_1_1.jpg",
                            Price = 440.0
                        },
                        new
                        {
                            Id = 17,
                            AvailableQuantity = 2,
                            ManufacturerId = 3,
                            Model = "Magic5 Lite",
                            OperatingSystem = "Android",
                            Photo = "https://istyle.rs/media/catalog/product/i/p/iphone_13_pink_pdp_image_position-1a__wwen_7_1_1.jpg",
                            Price = 195.0
                        },
                        new
                        {
                            Id = 18,
                            AvailableQuantity = 5,
                            ManufacturerId = 3,
                            Model = "X8a",
                            OperatingSystem = "Android",
                            Photo = "https://istyle.rs/media/catalog/product/i/p/iphone_13_pink_pdp_image_position-1a__wwen_7_1_1.jpg",
                            Price = 141.0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MobilePhoneStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MobilePhoneStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MobilePhoneStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MobilePhoneStore.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MobilePhoneStore.Models.Phone", b =>
                {
                    b.HasOne("MobilePhoneStore.Models.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufacturer");
                });
#pragma warning restore 612, 618
        }
    }
}
